package: community.lazycat.app.jellyfin
version: 10.11.11
name: Jellyfin
description: "A suite of multimedia applications"
min_os_version: 1.5.0
author: Jellyfin Team
homepage: https://jellyfin.org
license: GPL-2.0-only

locales:
  zh:
    name: "Jellyfin"
    description: "一套多媒体应用程序软件套装"
  en:
    name: "Jellyfin"
    description: "A suite of multimedia applications"

permissions:
  required:
    - net.internet
    - document.read
    - document.write
